version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
     - image: cimg/node:17.4.0
     ##cimg 新しいものに変更
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: yarn
      - run: 
          name: Building project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./dist/ s3://circle-ci-s3-deploy --delete

workflows:
  build:
    jobs:
      - build_project

      - deploy_project:
          requires:
            - build_project
          context: aws-context
          
